[theme]
primaryColor = "#8b5cf6"
backgroundColor = "#020204"
secondaryBackgroundColor = "#0c0d12"
textColor = "#f8fafc"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
